---
driver:
  name: ec2
  associate_public_ip: true
  require_chef_omnibus: true

transport:
  username: ec2-user

provisioner:
  name: chef_zero

platforms:
  - name: AmazonLinux-201807
    driver:
      image_id: ami-2a69be4c

suites:
  - name: default
    run_list:
      - recipe[aws-opsworks-cookbooks::default]
      - recipe[aws-opsworks-cookbooks::timezone]
      - recipe[aws-opsworks-cookbooks::setup-php56]
      - recipe[aws-opsworks-cookbooks::setup-postgresql96]
      - recipe[aws-opsworks-cookbooks::setup-services]
      - recipe[aws-opsworks-cookbooks::test-dmp]
      - recipe[aws-opsworks-cookbooks::configure-httpd]
      - recipe[aws-opsworks-cookbooks::configure-database]
      - recipe[aws-opsworks-cookbooks::deploy]

    data_bugs_path: "test/integration/default/data_bags"
    attributes:
    

